POST http://localhost:5000/api/bills/split 
Content-Type: application/json

{
    "bill":{
        "Akash":500,
        "Vikash":600,
        "Prakash":5000
    },
    "userId":"1432f36c-0fbb-4f4e-a2db-b4c01b26b5bc"
}

### 

POST http://localhost:5000/api/user/add HTTP/1.1
Content-Type: application/json

{
    "name":"Akash"
}

###

GET http://localhost:5000/api/user/history/1432f36c-0fbb-4f4e-a2db-b4c01b26b5bc HTTP/1.1
