const SPLIT_REQUEST = "SPLIT_REQUEST";
const SPLIT_SUCCESS = "SPLIT_SUCCESS";
const SPLIT_FAILUER = "SPLIT_FAILUER";
const HISTORY_REQUEST = "HISTORY_REQUEST";
const HISTORY_SUCCESS = "HISTORY_SUCCESS";
const HISTORY_FAILUER = "HISTORY_FAILUER";

export {
  HISTORY_FAILUER,
  HISTORY_SUCCESS,
  HISTORY_REQUEST,
  SPLIT_FAILUER,
  SPLIT_SUCCESS,
  SPLIT_REQUEST,
};
